project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Data Integration"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/data-driven-workflows.qmd
        - text: "---"
        - topics/azure-data-lake-storage.qmd
        - text: "---"
        - topics/compare-azure-data-lake-to-azure-blob-storage.qmd
        - text: "---"
        - topics/azure-databricks.qmd
        - text: "---"
        - topics/azure-synapse-analytics.qmd
        - text: "---"
        - topics/compare-azure-data-factory-to-azure-synapse-analytics.qmd        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
